import { ScannedDocument } from '@/types/student';

export const INITIAL_SCANNED_DOCUMENTS: ScannedDocument[] = [
  {
    id: 'DOC-2026-001',
    title: 'សំបុត្រកំណើត - សុខ វិសាល',
    category: 'សំបុត្រកំណើត',
    grade: 8,
    studentId: 'HSS-2026-0001',
    studentNameKhmer: 'សុខ វិសាល',
    studentNameLatin: 'SOK VISAL',
    dob: '2012-05-15',
    dobKhmer: 'ថ្ងៃទី១៥ ខែឧសភា ឆ្នាំ២០១២',
    gender: 'ប្រុស',
    pob: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    fatherName: 'សុខ វិបុល',
    motherName: 'ម៉ៅ សុខា',
    fileDataUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=600&auto=format&fit=crop&q=80',
    scannedAt: '2026-06-02',
    classificationReason: 'សិស្សកើតឆ្នាំ២០១២ (អាយុ១៤ឆ្នាំ) និងមានអត្តលេខថ្នាក់ទី៨ នៅក្នុងប្រព័ន្ធ -> តម្រៀបចូលថតថ្នាក់ទី ៨ អូតូ',
    confidenceScore: 98,
    notes: 'ច្បាប់ដើមសំបុត្រកំណើតច្បាស់លាស់ ហត្ថលេខាមេឃុំសូទិព្វ',
  },
  {
    id: 'DOC-2026-002',
    title: 'សៀវភៅតាមដានការសិក្សា - ចាន់ ស្រីនីត',
    category: 'សៀវភៅតាមដានការសិក្សា',
    grade: 8,
    studentId: 'HSS-2026-0002',
    studentNameKhmer: 'ចាន់ ស្រីនីត',
    studentNameLatin: 'CHAN SREYNITH',
    dob: '2012-11-20',
    dobKhmer: 'ថ្ងៃទី២០ ខែវិច្ឆិកា ឆ្នាំ២០១២',
    gender: 'ស្រី',
    pob: 'ភូមិព្រៃទទឹង ឃុំព្រៃចារ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    fatherName: 'ចាន់ ធឿន',
    motherName: 'សេង ផល្លា',
    fileDataUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&auto=format&fit=crop&q=80',
    scannedAt: '2026-06-02',
    classificationReason: 'សៀវភៅតាមដានបញ្ជាក់លទ្ធផលបញ្ចប់ថ្នាក់ទី៧ ឡើងថ្នាក់ទី៨ -> តម្រៀបចូលថតថ្នាក់ទី ៨ អូតូ',
    confidenceScore: 99,
    notes: 'មធ្យមភាគប្រចាំឆ្នាំ ៨.២៥ ចំណាត់ថ្នាក់លេខ ៥ ឡើងថ្នាក់',
  },
  {
    id: 'DOC-2026-003',
    title: 'វិញ្ញាបនបត្របឋមសិក្សា - កែវ សំណាង',
    category: 'វិញ្ញាបនបត្របឋមសិក្សា',
    grade: 7,
    studentId: 'HSS-2026-0006',
    studentNameKhmer: 'កែវ សំណាង',
    studentNameLatin: 'KEO SAMNANG',
    dob: '2013-09-08',
    dobKhmer: 'ថ្ងៃទី០៨ ខែកញ្ញា ឆ្នាំ២០១៣',
    gender: 'ប្រុស',
    pob: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    fatherName: 'កែវ សុខុម',
    motherName: 'នួន ស្រីពៅ',
    fileDataUrl: 'https://images.unsplash.com/photo-1544717302-de2939b7ef71?w=600&auto=format&fit=crop&q=80',
    scannedAt: '2026-06-03',
    classificationReason: 'វិញ្ញាបនបត្របញ្ចប់ការសិក្សាបឋមសិក្សា (ថ្នាក់ទី៦) -> ចុះឈ្មោះចូលរៀនថ្នាក់ទី ៧ អូតូ',
    confidenceScore: 100,
    notes: 'ប្រឡងជាប់បញ្ចប់បឋមសិក្សាអនុវត្តន៍ស្គន់ និទ្ទេសល្អ',
  },
  {
    id: 'DOC-2026-004',
    title: 'លិខិតផ្ទេរការសិក្សា - ហេង សុវណ្ណារ៉ា',
    category: 'លិខិតផ្ទេរការសិក្សា',
    grade: 9,
    studentId: 'HSS-2026-0004',
    studentNameKhmer: 'ហេង សុវណ្ណារ៉ា',
    studentNameLatin: 'HENG SOVANNARA',
    dob: '2011-04-10',
    dobKhmer: 'ថ្ងៃទី១០ ខែមេសា ឆ្នាំ២០១១',
    gender: 'ប្រុស',
    pob: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    fatherName: 'ហេង ប៊ុនថន',
    motherName: 'អ៊ុក គឹមលាង',
    fileDataUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    scannedAt: '2026-06-03',
    classificationReason: 'លិខិតផ្ទេរចូលពីអនុវិទ្យាល័យព្រៃទទឹង បញ្ជាក់ឡើងថ្នាក់ទី៩ -> តម្រៀបចូលថតថ្នាក់ទី ៩ អូតូ',
    confidenceScore: 97,
    notes: 'លិខិតផ្ទេរផ្លូវការមានត្រាការិយាល័យអប់រំស្រុក',
  },
  {
    id: 'DOC-2026-005',
    title: 'ប័ណ្ណសមធម៌ក្រីក្រ - រស់ មុនី',
    category: 'ប័ណ្ណសមធម៌ក្រីក្រ',
    grade: 8,
    studentId: 'HSS-2026-0003',
    studentNameKhmer: 'រស់ មុនី',
    studentNameLatin: 'ROS MONY',
    dob: '2012-08-04',
    dobKhmer: 'ថ្ងៃទី០៤ ខែសីហា ឆ្នាំ២០១២',
    gender: 'ប្រុស',
    pob: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    fatherName: 'រស់ ចំរើន',
    motherName: 'លឹម គឹមសួរ',
    fileDataUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    scannedAt: '2026-06-04',
    classificationReason: 'ប័ណ្ណមូលនិធិសមធម៌សុខាភិបាល/ក្រីក្រកម្រិត១ របស់សិស្សថ្នាក់ទី៨ រស់ មុនី -> ថតថ្នាក់ទី ៨ អូតូ',
    confidenceScore: 99,
    notes: 'ប័ណ្ណក្រីក្រលេខ ០៣០២០១០៤៥ សុពលភាពដល់ឆ្នាំ២០២៧ ទទួលបានអាហារូបករណ៍',
  },
  {
    id: 'DOC-2026-006',
    title: 'ពាក្យសុំចុះឈ្មោះចូលរៀន - តែ សុជាតា',
    category: 'ពាក្យសុំចុះឈ្មោះចូលរៀន',
    grade: 12,
    studentId: 'HSS-2026-0005',
    studentNameKhmer: 'តែ សុជាតា',
    studentNameLatin: 'TEA SOCHEATA',
    dob: '2008-01-25',
    dobKhmer: 'ថ្ងៃទី២៥ ខែមករា ឆ្នាំ២០០៨',
    gender: 'ស្រី',
    pob: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    fatherName: 'តែ គឹមស៊ាង',
    motherName: 'អ៊ុច ស្រីមុំ',
    fileDataUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
    scannedAt: '2026-06-04',
    classificationReason: 'ពាក្យសុំចុះឈ្មោះសិស្សបាក់ឌុប ផ្នែកវិទ្យាសាស្ត្រ (ថ្នាក់ទី១២) -> តម្រៀបចូលថតថ្នាក់ទី ១២ អូតូ',
    confidenceScore: 98,
    notes: 'សិស្សត្រៀមប្រឡងសញ្ញាបត្រមធ្យមសិក្សាទុតិយភូមិ ២០២៦-២០២៧',
  }
];

// Sample test templates that the user can click to test the auto-scan & OCR feature without uploading a file
export const SAMPLE_SCAN_TEMPLATES = [
  {
    name: 'សំបុត្រកំណើតសិស្សថ្នាក់ទី ៨ (គំរូផ្លូវការ)',
    badge: 'ថ្នាក់ទី ៨ អូតូ',
    category: 'សំបុត្រកំណើត' as const,
    grade: 8 as const,
    khmerName: 'នួន រតនៈ',
    latinName: 'NOUN RATANAK',
    gender: 'ប្រុស' as const,
    dob: '2012-07-18',
    dobKhmer: 'ថ្ងៃទី១៨ ខែកក្កដា ឆ្នាំ២០១២',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    fatherName: 'នួន វណ្ណា',
    motherName: 'ស៊ឹម វល័ក្ខ',
    reason: 'សំបុត្រកំណើតបញ្ជាក់ឆ្នាំកំណើត ២០១២ (អាយុ១៤ឆ្នាំ) និងបញ្ចប់ថ្នាក់ទី៧ -> ចាត់ថ្នាក់ចូលថត ថ្នាក់ទី ៨ ដោយស្វ័យប្រវត្តិ',
    fileUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=80',
    textSnippet: `ព្រះរាជាណាចក្រកម្ពុជា ជាតិ សាសនា ព្រះមហាក្សត្រ\nសំបុត្រកំណើត\nសាលាឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម\nកុមារឈ្មោះ: នួន រតនៈ (NOUN RATANAK) ភេទ: ប្រុស\nកើតថ្ងៃទី: ១៨ ខែកក្កដា ឆ្នាំ២០១២\nឪពុក: នួន វណ្ណា ម្តាយ: ស៊ឹម វល័ក្ខ\nទីកន្លែងកំណើត: ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម`
  },
  {
    name: 'វិញ្ញាបនបត្របញ្ចប់បឋមសិក្សា (គំរូចុះថ្នាក់ទី ៧)',
    badge: 'ថ្នាក់ទី ៧ អូតូ',
    category: 'វិញ្ញាបនបត្របឋមសិក្សា' as const,
    grade: 7 as const,
    khmerName: 'សេង ចរិយា',
    latinName: 'SENG CHHARIYA',
    gender: 'ស្រី' as const,
    dob: '2013-10-12',
    dobKhmer: 'ថ្ងៃទី១២ ខែតុលា ឆ្នាំ២០១៣',
    pobVillage: 'ត្រពាំងស្លា',
    pobCommune: 'ព្រៃចារ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    fatherName: 'សេង វិចិត្រ',
    motherName: 'គង់ សោភា',
    reason: 'វិញ្ញាបនបត្របញ្ចប់ការសិក្សាបឋមសិក្សាថ្នាក់ទី៦ -> ចាត់ថ្នាក់ចូលថត ថ្នាក់ទី ៧ ដោយស្វ័យប្រវត្តិ',
    fileUrl: 'https://images.unsplash.com/photo-1544717302-de2939b7ef71?w=800&auto=format&fit=crop&q=80',
    textSnippet: `ក្រសួងអប់រំ យុវជន និងកីឡា\nវិញ្ញាបនបត្របញ្ចប់ការសិក្សាបឋមសិក្សា\nបញ្ជាក់ថាសិស្សឈ្មោះ: សេង ចរិយា (SENG CHHARIYA) ភេទ: ស្រី\nកើតថ្ងៃទី: ១២ ខែតុលា ឆ្នាំ២០១៣\nបានបញ្ចប់ថ្នាក់ទី៦ ដោយជោគជ័យ និងមានសិទ្ធិចុះឈ្មោះចូលរៀនថ្នាក់ទី៧ នៅវិទ្យាល័យ ហ៊ុន សែន ស្គន់`
  },
  {
    name: 'លិខិតផ្ទេរការសិក្សាឡើងថ្នាក់ទី ១០ (គំរូផ្លូវការ)',
    badge: 'ថ្នាក់ទី ១០ អូតូ',
    category: 'លិខិតផ្ទេរការសិក្សា' as const,
    grade: 10 as const,
    khmerName: 'ហុក ពិសិដ្ឋ',
    latinName: 'HOK PISETH',
    gender: 'ប្រុស' as const,
    dob: '2010-03-22',
    dobKhmer: 'ថ្ងៃទី២២ ខែមីនា ឆ្នាំ២០១០',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    fatherName: 'ហុក សុផល',
    motherName: 'លាង ចន្ថា',
    reason: 'លិខិតផ្ទេរបញ្ជាក់ប្រឡងជាប់សញ្ញាបត្រមធ្យមសិក្សាបឋមភូមិ (ឌីប្លូម) ឡើងថ្នាក់ទី១០ -> ចាត់ថ្នាក់ចូលថត ថ្នាក់ទី ១០ ដោយស្វ័យប្រវត្តិ',
    fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    textSnippet: `លិខិតផ្ទេរការសិក្សា\nក្រសួងអប់រំ យុវជន និងកីឡា\nសិស្សឈ្មោះ: ហុក ពិសិដ្ឋ (HOK PISETH) ភេទ: ប្រុស\nកើតថ្ងៃទី: ២២ ខែមីនា ឆ្នាំ២០១០\nបានប្រឡងជាប់សញ្ញាបត្រមធ្យមសិក្សាបឋមភូមិ (ឌីប្លូម) សម័យប្រឡង ២០២៥\nអនុញ្ញាតឱ្យផ្ទេរចូលរៀនថ្នាក់ទី ១០ វិទ្យាល័យ ហ៊ុន សែន ស្គន់`
  },
  {
    name: 'ប័ណ្ណសមធម៌ក្រីក្រ និងអាហារូបករណ៍',
    badge: 'ថ្នាក់ទី ៨ អូតូ',
    category: 'ប័ណ្ណសមធម៌ក្រីក្រ' as const,
    grade: 8 as const,
    khmerName: 'ជួប វណ្ណឌី',
    latinName: 'CHUOB VANDY',
    gender: 'ប្រុស' as const,
    dob: '2012-02-14',
    dobKhmer: 'ថ្ងៃទី១៤ ខែកុម្ភៈ ឆ្នាំ២០១២',
    pobVillage: 'សូទិព្វ',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    fatherName: 'ជួប ផាន់',
    motherName: 'ប៉ុក យីន',
    reason: 'ប័ណ្ណក្រីក្រកម្រិត១ របស់សិស្សអាយុ១៤ឆ្នាំ -> ចាត់ថ្នាក់ចូលថត ថ្នាក់ទី ៨ និងស្នើផ្តល់អាហារូបករណ៍រដ្ឋ',
    fileUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    textSnippet: `ប័ណ្ណសមធម៌មូលនិធិគាំពារសង្គម\nលេខកូដគ្រួសារ: IDP-0302-9988\nកម្រិតក្រីក្រ: កម្រិត១ (ក្រីក្រខ្លាំង)\nសមាជិកគ្រួសារ: ជួប វណ្ណឌី (CHUOB VANDY) កើតឆ្នាំ: ២០១២\nឪពុក: ជួប ផាន់ ម្តាយ: ប៉ុក យីន\nភូមិសូទិព្វ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម`
  }
];
