import { SchoolInfo, Student } from '@/types/student';

export const DEFAULT_SCHOOL_INFO: SchoolInfo = {
  name: 'វិទ្យាល័យ ហ៊ុនសែន ស្គន់',
  ministry: 'ក្រសួងអប់រំ យុវជន និងកីឡា',
  department: 'មន្ទីរអប់រំ យុវជន និងកីឡា ខេត្តកំពង់ចាម',
  office: 'ការិយាល័យអប់រំ យុវជន និងកីឡា ស្រុកជើងព្រៃ',
  academicYear: '២០២៦-២០២៧',
  defaultGrade: 8,
  locationName: 'ស្គន់',
  lunarDate: 'ថ្ងៃអង្គារ ២រោច ខែជេស្ឋ ឆ្នាំមមី អដ្ឋស័ក ព.ស.២៥៧០',
  solarDate: 'ថ្ងៃទី២ ខែមិថុនា ឆ្នាំ២០២៦',
  principalName: 'លោកគ្រូ នាយកវិទ្យាល័យ',
  deputyPrincipalName: 'លោកគ្រូ នាយករង',
  phone: '០៤២ ៩៤១ ២៣៤ / ០១២ ៣៤៥ ៦៧៨',
  email: 'hunsenskun.hs@moeys.gov.kh',
  address: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម (រង្វង់មូលស្គន់)',
};

export const INITIAL_STUDENTS: Student[] = [
  // ថ្នាក់ទី ៨ (Grade 8 Focus as requested)
  {
    id: 'HSS-2026-0801',
    studentCode: '0801',
    khmerName: 'សុខ វិសាល',
    latinName: 'SOK VISAL',
    gender: 'ប្រុស',
    dob: '2012-04-15',
    dobKhmer: 'ថ្ងៃទី១៥ ខែមេសា ឆ្នាំ២០១២',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 8,
    classroom: '8A',
    track: 'ទូទៅ',
    status: 'ឡើងថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 44,
    height: 153,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'សុខ គឹមហុង',
    fatherJob: 'កសិករ',
    fatherPhone: '097 888 1234',
    motherName: 'យឹម សុគន្ធា',
    motherJob: 'អាជីវករ',
    motherPhone: '012 999 5678',
    guardianName: 'សុខ គឹមហុង',
    guardianPhone: '097 888 1234',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'សិស្សរៀនពូកែគណិតវិទ្យា',
  },
  {
    id: 'HSS-2026-0802',
    studentCode: '0802',
    khmerName: 'ចាន់ ស្រីនិច',
    latinName: 'CHAN SREYNICH',
    gender: 'ស្រី',
    dob: '2012-08-22',
    dobKhmer: 'ថ្ងៃទី២២ ខែសីហា ឆ្នាំ២០១២',
    pobVillage: 'ត្រពាំងស្លា',
    pobCommune: 'ព្រៃចារ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិត្រពាំងស្លា ឃុំព្រៃចារ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 8,
    classroom: '8A',
    track: 'ទូទៅ',
    status: 'ឡើងថ្នាក់',
    scholarship: true,
    poorLevel: 'កម្រិត២ (ក្រីក្រ)',
    hasDisability: false,
    weight: 39,
    height: 147,
    visionLevel: 'ខ្សោយមធ្យម',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ក្រីក្រកម្រិត២',
    fatherName: 'ចាន់ វណ្ណា',
    fatherJob: 'សំណង់',
    fatherPhone: '088 777 3344',
    motherName: 'ហេង ម៉ាលី',
    motherJob: 'កសិករ',
    motherPhone: '071 222 9988',
    guardianName: 'ហេង ម៉ាលី',
    guardianPhone: '071 222 9988',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'សិស្សទទួលបានអាហារូបករណ៍សមធម៌',
  },
  {
    id: 'HSS-2026-0803',
    studentCode: '0803',
    khmerName: 'ហេង រតនា',
    latinName: 'HENG RATTANA',
    gender: 'ប្រុស',
    dob: '2012-01-10',
    dobKhmer: 'ថ្ងៃទី១០ ខែមករា ឆ្នាំ២០១២',
    pobVillage: 'ផ្តៅជុំ',
    pobCommune: 'ផ្តៅជុំ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិផ្តៅជុំ ឃុំផ្តៅជុំ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 8,
    classroom: '8A',
    track: 'ទូទៅ',
    status: 'ឡើងថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 48,
    height: 156,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'ហេង សម្បត្តិ',
    fatherJob: 'មន្ត្រីរាជការ',
    fatherPhone: '012 345 678',
    motherName: 'កែវ សោភា',
    motherJob: 'គ្រូបង្រៀន',
    motherPhone: '015 678 901',
    guardianName: 'ហេង សម្បត្តិ',
    guardianPhone: '012 345 678',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: '',
  },
  {
    id: 'HSS-2026-0804',
    studentCode: '0804',
    khmerName: 'កែវ មុន្នីរ័ត្ន',
    latinName: 'KEO MONIROTH',
    gender: 'ស្រី',
    dob: '2012-11-05',
    dobKhmer: 'ថ្ងៃទី០៥ ខែវិច្ឆិកា ឆ្នាំ២០១២',
    pobVillage: 'សំបូរ',
    pobCommune: 'សំបូរ',
    pobDistrict: 'បាធាយ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 8,
    classroom: '8B',
    track: 'ទូទៅ',
    status: 'ផ្ទេរចូល',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 42,
    height: 151,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'កែវ ចំរើន',
    fatherJob: 'បើកបររថយន្ត',
    fatherPhone: '092 111 222',
    motherName: 'នួន ស្រីពៅ',
    motherJob: 'មេផ្ទះ',
    motherPhone: '097 333 444',
    guardianName: 'កែវ ចំរើន',
    guardianPhone: '092 111 222',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'ផ្ទេរមកពីអនុវិទ្យាល័យបាធាយ',
  },
  {
    id: 'HSS-2026-0805',
    studentCode: '0805',
    khmerName: 'លី សុខុម',
    latinName: 'LY SOKHUM',
    gender: 'ប្រុស',
    dob: '2011-12-18',
    dobKhmer: 'ថ្ងៃទី១៨ ខែធ្នូ ឆ្នាំ២០១១',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 8,
    classroom: '8B',
    track: 'ទូទៅ',
    status: 'ត្រួតថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: true,
    disabilityInfo: 'ពិការជើងឆ្វេងកម្រិតស្រាល',
    weight: 46,
    height: 155,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ខ្សោយមធ្យម',
    limbDisability: 'ពិការជើងឆ្វេងស្រាល',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'លី ថន',
    fatherJob: 'ជាងម៉ូតូ',
    fatherPhone: '088 998 7766',
    motherName: 'អ៊ឹង ម៉ុម',
    motherJob: 'លក់ដូរនៅផ្សារស្គន់',
    motherPhone: '016 554 433',
    guardianName: 'អ៊ឹង ម៉ុម',
    guardianPhone: '016 554 433',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'សិស្សពិការជើងឆ្វេង និងពិបាកស្តាប់បន្តិច អង្គុយតុមុខ',
  },
  {
    id: 'HSS-2026-0806',
    studentCode: '0806',
    khmerName: 'គឹម ស្រីលក្ខណ៍',
    latinName: 'KIM SREYLEAK',
    gender: 'ស្រី',
    dob: '2012-03-30',
    dobKhmer: 'ថ្ងៃទី៣០ ខែមីនា ឆ្នាំ២០១២',
    pobVillage: 'ស្រយ៉ូវ',
    pobCommune: 'ស្រយ៉ូវ',
    pobDistrict: 'ស្ទឹងសែន',
    pobProvince: 'កំពង់ធំ',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 8,
    classroom: '8B',
    track: 'ទូទៅ',
    status: 'សិស្សថ្មី',
    scholarship: true,
    poorLevel: 'កម្រិត១ (ក្រីក្រខ្លាំង)',
    hasDisability: false,
    weight: 36,
    height: 144,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'ហឺត (Asthma)',
    familyStatusLevel: 'ក្រីក្រកម្រិត១',
    fatherName: 'គឹម ហេង',
    fatherJob: 'កម្មករ',
    fatherPhone: '097 555 1212',
    motherName: 'សេង គឹមលាង',
    motherJob: 'កម្មការិនីកាត់ដេរ',
    motherPhone: '096 444 3322',
    guardianName: 'គឹម ហេង',
    guardianPhone: '097 555 1212',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'មានប័ណ្ណក្រីក្រកម្រិត១ ទទួលបានកញ្ចប់ឧបត្ថម្ភការសិក្សា',
  },

  // ថ្នាក់ទី ៧ (Grade 7)
  {
    id: 'HSS-2026-0701',
    studentCode: '0701',
    khmerName: 'ម៉ៅ ពិសិដ្ឋ',
    latinName: 'MAO PISETH',
    gender: 'ប្រុស',
    dob: '2013-05-14',
    dobKhmer: 'ថ្ងៃទី១៤ ខែមេសា ឆ្នាំ២០១៣',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 7,
    classroom: '7A',
    track: 'ទូទៅ',
    status: 'សិស្សថ្មី',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 38,
    height: 145,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'ម៉ៅ សារ៉ាត',
    fatherJob: 'អាជីវករលក់ចំណីអាហារ',
    fatherPhone: '092 888 777',
    motherName: 'យន់ ចិន្តា',
    motherJob: 'មេផ្ទះ',
    motherPhone: '087 665 544',
    guardianName: 'ម៉ៅ សារ៉ាត',
    guardianPhone: '092 888 777',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'សិស្សប្រឡងជាប់បឋមសិក្សាស្គន់ និទ្ទេសល្អ',
  },
  {
    id: 'HSS-2026-0702',
    studentCode: '0702',
    khmerName: 'នួន ទេវី',
    latinName: 'NUON TEVY',
    gender: 'ស្រី',
    dob: '2013-09-08',
    dobKhmer: 'ថ្ងៃទី០៨ ខែកញ្ញា ឆ្នាំ២០១៣',
    pobVillage: 'គោករវៀង',
    pobCommune: 'គោករវៀង',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិគោករវៀង ឃុំគោករវៀង ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 7,
    classroom: '7A',
    track: 'ទូទៅ',
    status: 'សិស្សថ្មី',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 35,
    height: 142,
    visionLevel: 'ខ្សោយមធ្យម',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'នួន វិបុល',
    fatherJob: 'កសិករ',
    fatherPhone: '088 443 3221',
    motherName: 'ពេជ្រ ចរិយា',
    motherJob: 'កសិករ',
    motherPhone: '097 221 1009',
    guardianName: 'នួន វិបុល',
    guardianPhone: '088 443 3221',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'ពាក់វ៉ែនតាភ្នែក',
  },

  // ថ្នាក់ទី ៩ (Grade 9)
  {
    id: 'HSS-2026-0901',
    studentCode: '0901',
    khmerName: 'អ៊ុក ដារ៉ា',
    latinName: 'OUK DARA',
    gender: 'ប្រុស',
    dob: '2011-02-28',
    dobKhmer: 'ថ្ងៃទី២៨ ខែកុម្ភៈ ឆ្នាំ២០១១',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 9,
    classroom: '9A',
    track: 'ទូទៅ',
    status: 'ឡើងថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 50,
    height: 160,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'អ៊ុក សារឿន',
    fatherJob: 'ជាងសំណង់',
    fatherPhone: '012 887 766',
    motherName: 'តែ ស្រីមុំ',
    motherJob: 'លក់ចាប់ហួយ',
    motherPhone: '010 334 455',
    guardianName: 'អ៊ុក សារឿន',
    guardianPhone: '012 887 766',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'ត្រៀមប្រឡងសញ្ញាបត្របឋមភូមិ (ឌីប្លូម)',
  },
  {
    id: 'HSS-2026-0902',
    studentCode: '0902',
    khmerName: 'យឹម ចរិយា',
    latinName: 'YIM CHORIYA',
    gender: 'ស្រី',
    dob: '2011-07-19',
    dobKhmer: 'ថ្ងៃទី១៩ ខែកក្កដា ឆ្នាំ២០១១',
    pobVillage: 'ព្រៃទទឹង',
    pobCommune: 'ព្រៃទទឹង',
    pobDistrict: 'ព្រៃឈរ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 9,
    classroom: '9A',
    track: 'ទូទៅ',
    status: 'ឡើងថ្នាក់',
    scholarship: true,
    poorLevel: 'កម្រិត២ (ក្រីក្រ)',
    hasDisability: false,
    weight: 43,
    height: 153,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ក្រីក្រកម្រិត២',
    fatherName: 'យឹម ផល្លា',
    fatherJob: 'កសិករ',
    fatherPhone: '097 765 4321',
    motherName: 'ឡុង ពិសី',
    motherJob: 'កសិករ',
    motherPhone: '071 889 9001',
    guardianName: 'យឹម ផល្លា',
    guardianPhone: '097 765 4321',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: '',
  },

  // ថ្នាក់ទី ១០ (Grade 10)
  {
    id: 'HSS-2026-1001',
    studentCode: '1001',
    khmerName: 'ឈន វុទ្ធី',
    latinName: 'CHHORN VUTHY',
    gender: 'ប្រុស',
    dob: '2010-06-12',
    dobKhmer: 'ថ្ងៃទី១២ ខែមិថុនា ឆ្នាំ២០១០',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 10,
    classroom: '10A',
    track: 'ទូទៅ',
    status: 'ឡើងថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 55,
    height: 164,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'ឈន វិចិត្រ',
    fatherJob: 'អាជីវករ',
    fatherPhone: '012 667 788',
    motherName: 'ខៀវ សុវណ្ណារី',
    motherJob: 'អាជីវករ',
    motherPhone: '017 334 455',
    guardianName: 'ឈន វិចិត្រ',
    guardianPhone: '012 667 788',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'ជាប់ឌីប្លូមនិទ្ទេសល្អ',
  },

  // ថ្នាក់ទី ១១ (Grade 11 - Science / Social)
  {
    id: 'HSS-2026-1101',
    studentCode: '1101',
    khmerName: 'តែ ប៊ុនធឿន',
    latinName: 'TE BUNTHOEUN',
    gender: 'ប្រុស',
    dob: '2009-10-03',
    dobKhmer: 'ថ្ងៃទី០៣ ខែតុលា ឆ្នាំ២០០៩',
    pobVillage: 'សូទិព្វ',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិសូទិព្វ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 11,
    classroom: '11A1',
    track: 'វិទ្យាសាស្ត្រ',
    status: 'ឡើងថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 58,
    height: 168,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'តែ វ៉ាន់នី',
    fatherJob: 'បុគ្គលិកធនាគារ',
    fatherPhone: '011 223 344',
    motherName: 'ប៉ែន ស្រីអូន',
    motherJob: 'គ្រូបង្រៀន',
    motherPhone: '012 556 677',
    guardianName: 'តែ វ៉ាន់នី',
    guardianPhone: '011 223 344',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'ថ្នាក់វិទ្យាសាស្ត្រពិត (គណិត រូប គីមី ជីវ)',
  },
  {
    id: 'HSS-2026-1102',
    studentCode: '1102',
    khmerName: 'រស់ ច័ន្ទណា',
    latinName: 'ROS CHANNA',
    gender: 'ស្រី',
    dob: '2009-04-18',
    dobKhmer: 'ថ្ងៃទី១៨ ខែមេសា ឆ្នាំ២០០៩',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 11,
    classroom: '11B1',
    track: 'វិទ្យាសាស្ត្រសង្គម',
    status: 'ឡើងថ្នាក់',
    scholarship: true,
    poorLevel: 'កម្រិត២ (ក្រីក្រ)',
    hasDisability: false,
    weight: 47,
    height: 156,
    visionLevel: 'ខ្សោយមធ្យម',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ក្រីក្រកម្រិត២',
    fatherName: 'រស់ ភារម្យ',
    fatherJob: 'កសិករ',
    fatherPhone: '088 123 4567',
    motherName: 'អ៊ុំ សារី',
    motherJob: 'កសិករ',
    motherPhone: '097 987 6543',
    guardianName: 'រស់ ភារម្យ',
    guardianPhone: '088 123 4567',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'ថ្នាក់វិទ្យាសាស្ត្រសង្គម (ប្រវត្តិ ភូមិ ពលរដ្ឋ អក្សរសាស្ត្រខ្មែរ)',
  },

  // ថ្នាក់ទី ១២ (Grade 12 - BacII candidates)
  {
    id: 'HSS-2026-1201',
    studentCode: '1201',
    khmerName: 'សេង វណ្ណដា',
    latinName: 'SENG VANNDA',
    gender: 'ប្រុស',
    dob: '2008-08-05',
    dobKhmer: 'ថ្ងៃទី០៥ ខែសីហា ឆ្នាំ២០០៨',
    pobVillage: 'ស្គន់',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិស្គន់ ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 12,
    classroom: '12A1',
    track: 'វិទ្យាសាស្ត្រ',
    status: 'ឡើងថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 62,
    height: 172,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'សេង ប៊ុន្នី',
    fatherJob: 'មន្ត្រីនគរបាល',
    fatherPhone: '012 909 090',
    motherName: 'ព្រុំ សុខា',
    motherJob: 'អាជីវករ',
    motherPhone: '015 808 080',
    guardianName: 'សេង ប៊ុន្នី',
    guardianPhone: '012 909 090',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'បេក្ខជនប្រឡងបាក់ឌុប ឆ្នាំសិក្សា២០២៦-២០២៧',
  },
  {
    id: 'HSS-2026-1202',
    studentCode: '1202',
    khmerName: 'ឡុង កល្យាណ',
    latinName: 'LONG KALYAN',
    gender: 'ស្រី',
    dob: '2008-12-14',
    dobKhmer: 'ថ្ងៃទី១៤ ខែធ្នូ ឆ្នាំ២០០៨',
    pobVillage: 'ត្រពាំងព្រលិត',
    pobCommune: 'សូទិព្វ',
    pobDistrict: 'ជើងព្រៃ',
    pobProvince: 'កំពង់ចាម',
    currentAddress: 'ភូមិត្រពាំងព្រលិត ឃុំសូទិព្វ ស្រុកជើងព្រៃ ខេត្តកំពង់ចាម',
    grade: 12,
    classroom: '12B1',
    track: 'វិទ្យាសាស្ត្រសង្គម',
    status: 'ឡើងថ្នាក់',
    scholarship: false,
    poorLevel: 'គ្មាន',
    hasDisability: false,
    weight: 49,
    height: 158,
    visionLevel: 'ធម្មតា',
    hearingLevel: 'ធម្មតា',
    limbDisability: 'គ្មាន',
    chronicDisease: 'គ្មាន',
    familyStatusLevel: 'ជីវភាពមធ្យម',
    fatherName: 'ឡុង សុធា',
    fatherJob: 'កសិករ',
    fatherPhone: '097 123 4999',
    motherName: 'គង់ វ៉ានី',
    motherJob: 'កសិករ',
    motherPhone: '088 987 6111',
    guardianName: 'ឡុង សុធា',
    guardianPhone: '097 123 4999',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80',
    registeredDate: '2026-06-02',
    notes: 'សិស្សឆ្នើមផ្នែកអក្សរសាស្ត្រខ្មែរ',
  },
];
